<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\TRCrypto.BinanceTR\TRCrypto.BinanceTR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fixtures\**\*.json" />
    <None Include="Endpoints\**\*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
